website/__init__.py
from flask import Flask
from .config import Config


def create_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(config)

    app.app_context().push()

    from .main.routes import main_bp
    app.register_blueprint(main_bp)

    return app

website/main/routes.py
import os
import uuid

from flask import *

main_bp = Blueprint('main_bp', __name__)

files_dir = os.path.join(current_app.root_path, 'files')


@main_bp.route('/')
def home():
    return render_template('home.html', generate_file_id=generate_file_id)


@main_bp.route('/edit/<file_id>')
def editor(file_id):
    file = os.path.join(files_dir, file_id + '.txt')
    if not os.path.exists(files_dir):
        os.mkdir(files_dir)
    if not os.path.exists(file):
        open(file, 'w').close()
    with open(file) as f:
        text = f.read()
    return render_template('editor.html', file_id=file_id, save=save, text=text)


@main_bp.route('/view/<file_id>')
def view(file_id):
    file = os.path.join(files_dir, file_id + '.txt')
    if not os.path.exists(files_dir):
        abort(400)
    file = open(file)
    text = file.read()
    file.close()
    # text = text.replace('\n', '<br>')
    return render_template('viewer.html', text=text, file_id=file_id)


@main_bp.route('/save/<file_id>', methods=['POST'])
def save(file_id):
    if 'text' in request.json.keys():
        text = request.json['text']
        if len(text) > 0:
            file = os.path.join(files_dir, file_id + '.txt')
            if os.path.exists(file):
                with open(file, 'w') as file_writeable:
                    file_writeable.write(text)
                # with open(file) as file_readable:
                #     print(file_readable.read())
                return '200'
            return '404'
    return '500'


def generate_file_id():
    if not os.path.exists(files_dir):
        os.mkdir(files_dir)
    file_id = uuid.uuid4().hex
    while os.path.exists(os.path.join(files_dir, file_id + '.txt')):
        file_id = uuid.uuid4().hex
    return file_id

#================errors========================

@main_bp.app_errorhandler(400)
def error_400():
    pass

website/templates/editor.html
{% extends "layout.html" %}
{% block content %}
<textarea id="ta-editor"></textarea>
<div onclick="save_text()" class="btn btn-success">Save</div>
<a href="{{ url_for('main_bp.view', file_id=file_id) }}"><div class="btn btn-info">Done</div></a>

<script>
    console.log(`{{ text }}`);
    console.log(typeof `{{ text }}`);
    if(String(`{{ text }}`).length > 0){
        document.getElementById('ta-editor').value = `{{ text }}`;
    }
    function save_text(){
        const text = document.getElementById('ta-editor').value;
        console.log(text);
        $.ajax({
            type : "POST",
            url : '{{ url_for('main_bp.save', file_id=file_id) }}',
            dataType: "json",
            data: JSON.stringify({"text": text}),
            contentType: 'application/json;charset=UTF-8',
            success: function (data) {
                if(data=="200")
                    alert("Text Saved Successfully!");
                else if(data=="500")
                    alert("Something went wrong! Failed to save!");
                console.log(data);
            }
        });
    }
</script>
{% endblock %}

website/templates/home.html
{% extends "layout.html" %}
{% block content %}
<h1>Welcome to <span class="text-share-home-box">text-share</span></h1>
<p>

    Create your own sharable text!<br>

</p>
<a href="{{ url_for('main_bp.editor', file_id=generate_file_id()) }}"><div class="btn btn-info">Create</div></a>
{% endblock %}

website/templates/layout.html
<!doctype html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <title>Flask Blog{% if title %} - {{ title }}{% endif %}</title>
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">text-share</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>
</header>

<main role="main" class="container">
    <div class="row">
        <div class="col-12 col-md-12">
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category,message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
    </div>
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

website/templates/viewer.html
{% extends "layout.html" %}
{% block content %}
<style>
    #viewer-div{
        white-space: pre-wrap;
    }
</style>
<div id="viewer-div" class="text-view">{{ text }}</div>
<a href="{{ url_for('main_bp.editor', file_id=file_id) }}"><div class="btn btn-warning mt-2">Edit</div></a>
{% endblock %}